### ISSUE TITLE
cn.topiam.employee.common.entity.account包下类缺失

### ISSUE THREAD

**Issue by chenrl** [topiam/eiam#13]
项目缺少2个类文件
cn.topiam.employee.common.entity.account.QUserHistoryPasswordEntity
cn.topiam.employee.common.entity.account.QUserEntity

**Comment by yunszhang** [comment]
mvn compile之后，会自动生成代码的

**Comment by yepingping** [comment]
这些缺少的类是因用了Querydsl。
所以要通过mvn compile之后，自动生成代码。对应的代码目标在target/generated-sources目录下。
之后通过IDEA 选中其目录，Mark Directory as -> generated sources root 。
IDEA File -> Invalidate Caches （可选是否操作）
最后引用的类就正常了。
