### ISSUE TITLE
missing class

### ISSUE THREAD

**Issue by Frogchar** [topiam/eiam#37]
eiam-common包缺失类QUserHistoryPasswordEntity，eiam-core包构建失败cn.topiam.employee.core.security.password.manager.DefaultPasswordPolicyManager#getHistoryPasswordValidator
![image](https://github.com/topiam/eiam/assets/52767992/a5352af3-caec-4f57-b995-97f6e95d8795)

**Comment by kaychain** [comment]
看一下官方文档的常见问题
https://eiam.topiam.cn/docs/faq/
